# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37a600b980f6e295079c1f98dc3be3f4824e5a5fc170a3c565fb623438ba41a4a7692b8654d05e15dde3ba300ec0bff6d74b3eed2d8594097a67f00f0c79dc1c

test:
  secret_key_base: 396633c41906b73128d3013787425b9ccd0d77f6ecac3a7270c282cde3dea4e9eb75046bce3e2631d5b6d5d12f782c5d80fd20e8a7516337dcca36b919b55cd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
